### PR TITLE
fix: exit with correct status code

### LINKED ISSUE #7: [Bug] It always exit with status-code 0 even with broken links
Hello! :wave:

Currently this utility, prints all the links of the website, and prints if they are valid or not.
If some links are unvalid, it's still exiting with a exit status code of 0.
However, I find that this utility could be really useful in CI, and it might make more sense to exit with 1 for exemple, so it failsthe CI if there are broken links.

### PR DESCRIPTION
**Pull request by Divlo**
Fixes #7

Notes:
- Added `@types/node` dev dependencies to improve type safety, notably for `process` for example, and also verifying that the user gives a URL as third argument. It can be out of scope of this PR, so feel free to tell me if you want to add that in a separated PR.
- Added a new test case in `test/cli-test.js`, but it only has the "happy-path" scenario where all links are valid. I'm not sure what website, we could take for the test, to verify that it exits with status code 1 if there are broken links.
- ESLint, Prettier and editorconfig are not configured on the project, I tried to follow the project conventions with the code already available, forgive me if I forgot a `;` or semicolon or something. :sweat_smile: However, it could be great to integrate these tools to improve consistency (could be done in a separate PR).

### CODE REVIEW

File: src/bin.ts [hunk 1]
```diff
@@ -1,15 +1,19 @@
 #!/usr/bin/env node
 import { awaken, AwakenResult } from './index.js';
 
-// @ts-ignore
-const process = globalThis.process;
 const str = process.argv[2];
+if (str == null) {
```
Comment (styfle) [inline src/bin.ts:5]:
```suggestion
if (!str) {
```

File: src/bin.ts [hunk 2]
```diff
@@ -18,4 +22,7 @@ await awaken({ url: initUrl, onAwaken, results });
 const end = Date.now();
 const seconds = (end - start) / 1000;
 console.log(`Done! Awakened ${results.size} links in ${seconds} seconds`);
-process.exit(0); // TODO: should this exit with 1 if there were errors?
\ No newline at end of file
+
+if (!isSuccessful) {
+  process.exitCode = 1;
+}
```
Comment (styfle) [inline src/bin.ts:28]:
```suggestion
process.exit(isSuccessful ? 0 : 1);
```

I had to use process.exit(0) to make sure the `fetch` didn't hang since it seems to keep the connections open even after all responses are complete

**Comment by styfle** [comment]
>  I'm not sure what website, we could take for the test, to verify that it exits with status code 1 if there are broken links.

I think we will need to add test fixtures and start up a local server to test these cases.

**Comment by styfle** [comment]
> ESLint, Prettier and editorconfig are not configured on the project

I haven't gotten around to it.

If you want to create another PR to fix it, lets use [vercel/style-guide](https://github.com/vercel/style-guide) as the starting point.

**Review by styfle — APPROVED** [review]
Great work, thanks! 🎉
